apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbuck-app
  labels:
    app: coinbuck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbuck
  template:
    metadata:
      labels:
        app: coinbuck
    spec:
      containers:
        - name: coinbuck
          image: <ACR_LOGIN_SERVER>/coinbuck-app:{{IMAGE_TAG}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"