apiVersion: autoscaling/v2             # Use the stable HPA API version
kind: HorizontalPodAutoscaler
metadata:
  name: coinbuck-hpa                   # Name of the HPA resource
spec:
  scaleTargetRef:                      # The object that the HPA will scale
    apiVersion: apps/v1                # Target is a Deployment
    kind: Deployment
    name: coinbuck-app                 # Must match the Deployment name
  minReplicas: 1                       # Minimum number of pods to keep running
  maxReplicas: 5                       # Maximum number of pods to scale up to
  metrics:
    - type: Resource                   # Scale based on a built-in resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60       # If average CPU >50%, scale up