FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .


FROM node:18-alpine
WORKDIR /app
COPY --from=build /app /app
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "index.js"]